confVersion: core/v1alpha1
declarations:
- backend:
    # My ancient (!) Apache server 
    name: baseOne
    kind: singleHost
    hosts:
    - address: http://10.100.1.243:80
routines:
- hostProgram:
    hosts: ['*.archway.hayoola.host']
    functions:
      - stage: receiveRequest
        instructions:
        - setBackend: baseOne