confVersion: core/v1alpha1
declarations:
- backend:
    name: baseOne
    kind: singleHost
    hosts:
    - address: 127.0.0.1:8088
routines:
- hostProgram:
    hosts: [www.example.com, example.com]
    functions:
      - stage: receiveRequest
        instructions:
        - setBackend: baseOne